project_id = "camina-app"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["camina://auth-callback"]
enable_confirmations = false

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
